export type GalpaoImagem = {
  id: string;
  storage_path: string;
  ordem: number;
  visivel_site: boolean;
  is_capa: boolean;
};

export type Galpao = {
  id: string;
  titulo: string;
  tipo: string;
  categoria: string;
  uso_terreno: string | null;
  valor: number | null;
  cidade: string;
  bairro: string | null;
  endereco: string | null;
  cep: string | null;
  publicado: boolean;
  area_construida_m2: number | null;
  area_total_m2: number | null;
  area_piso_m2: number | null;
  pe_direito_m: number | null;
  numero_docas: number;
  acesso_carreta: boolean;
  sprinklers: boolean;
  sprinkler_tipo: string | null;
  guarita: boolean;
  potencia_eletrica_kva: number | null;
  capacidade_piso_ton_m2: number | null;
  area_escritorio_m2: number | null;
  truck_court_m: number | null;
  avcb_numero: string | null;
  avcb_validade: string | null;
  acessos_viarios: string | null;
  video_url: string | null;
  planta_baixa_url: string | null;
  vagas_estacionamento: number;
  condominio: boolean;
  valor_condominio: number | null;
  descricao: string | null;
  observacoes: string | null;
  campos_visibilidade: Record<string, { card: boolean; ficha: boolean }>;
  latitude: number | null;
  longitude: number | null;
  galpao_imagens: GalpaoImagem[];
};

// Tipo para a grid pública — subconjunto dos campos exibidos ao visitante
export type GalpaoPublico = {
  id: string;
  titulo: string;
  tipo: string;
  categoria: string;
  uso_terreno: string | null;
  valor: number | null;
  cidade: string;
  bairro: string | null;
  area_construida_m2: number | null;
  area_total_m2: number | null;
  pe_direito_m: number | null;
  numero_docas: number;
  acesso_carreta: boolean;
  potencia_eletrica_kva: number | null;
  capacidade_piso_ton_m2: number | null;
  avcb_validade: string | null;
  vagas_estacionamento: number;
  descricao: string | null;
  campos_visibilidade?: Record<string, { card: boolean; ficha: boolean }>;
  galpao_imagens: { storage_path: string; ordem: number; is_capa?: boolean }[];
};
